apiVersion: apps/v1
kind: Deployment
metadata:
  name: dark-matter-web-deployment
  namespace: dark-matter-web-prod
  labels:
    app: dark-matter-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dark-matter-web
  template:
    metadata:
      labels:
        app: dark-matter-web
    spec:
      containers:
        - name: web-server
          image: mvpstudio/darkmatterweb:July28
          resources:
            limits:
              cpu: 0.25
              memory: 250Mi
            requests:
              cpu: 0.25
              memory: 250Mi
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
