apiVersion: v1
kind: Service
metadata:
  name: dark-matter-web
  namespace: dark-matter-web-prod
spec:
  selector:
    app: dark-matter-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
